basic:
  input_size: 1600
  #input_size: 1024
  output_size: 500
  seed: 1

loss:
  MSE_t: 1
  LPIPS_t: 0

dir:
  save_model_dir: /home/ponoma/workspace/Lensless_Imaging_Transformer/checkpoints/   
  load_model_dir: /home/ponoma/workspace/Lensless_Imaging_Transformer/checkpoints/
  val_pattern_dir: /home/ponoma/workspace/Lensless_Imaging_Transformer/im1.npy    # TODO: what is this?
  val_rec_dir: /home/ponoma/workspace/Lensless_Imaging_Transformer/checkpoints/
  dataset_dir: /home/ponoma/workspace/Lensless_Imaging_Transformer/datasets/


train:
  GPU_num: 2
  load: False # TODO: changed this because no model to load
  num_steps: 450000
  eval_every: 15000
  train_batch_size: 3

optimizer:
  optimizer: AdamW
  learning_rate: 6e-5
  weight_decay: 0.1

scheduler:
  use: True
  warmup_steps: 0
